# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 500e58fc6faab90cb6efdaf143d46f0948b60501e032470a695ddba52d651a434b7253e9ca43a9037163d6e19d69908eae6913025d1263bf50810c6bb9f5c123

test:
  secret_key_base: 99757d3eb999ea293bb164cdbf73539a782ba8e1bddcc9a7c9a598acf9abce9b46e12b10a1aa47527fe29ae35885b269ca71761363cd21f838d087a2c5acda3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
